### PR TITLE
Fix build libretro PS3/PSL1GHT systems

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by irixxxx** [comment]
@crystalct, could you probably bring this up to current libchdr master and PR it directly to their repo? I'm going to update all submodules to the current versions anyway before merging that to lr-picodrive.

**Comment by crystalct** [comment]
Yes, was committed on Apr 29, 2021

**Comment by irixxxx** [comment]
I've pulled libchdr master some time ago and think this should be resolved. Would you please check and if so, close this?

**Comment by crystalct** [comment]
You can close ^_^

**Pull request closed without merging**
